# Generated by Django 4.2.2 on 2023-06-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company_name', models.CharField(max_length=130)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
